.....................................
Creating and compiling model ...
.....................................
Training model ...
2022-11-03 08:29:02.381841: W tensorflow/core/grappler/optimizers/data/auto_shard.cc:695] AUTO sharding policy will apply DATA sharding policy as it failed to apply FILE sharding policy because of the following reason: Found an unshardable source dataset: name: "TensorSliceDataset/_1"
op: "TensorSliceDataset"
input: "Placeholder/_0"
attr {
  key: "Toutput_types"
  value {
    list {
      type: DT_STRING
    }
  }
}
attr {
  key: "output_shapes"
  value {
    list {
      shape {
      }
    }
  }
}

2022-11-03 08:29:02.393400: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)
Epoch 1/100

Epoch 00001: LearningRateScheduler setting learning rate to 1e-07.
2022-11-03 08:29:44.081881: I tensorflow/stream_executor/cuda/cuda_dnn.cc:369] Loaded cuDNN version 8401
2022-11-03 08:29:45.728358: I tensorflow/stream_executor/cuda/cuda_dnn.cc:369] Loaded cuDNN version 8401
2022-11-03 08:29:46.595727: I tensorflow/stream_executor/cuda/cuda_dnn.cc:369] Loaded cuDNN version 8401
2022-11-03 08:29:48.006744: I tensorflow/stream_executor/cuda/cuda_dnn.cc:369] Loaded cuDNN version 8401
261/261 [==============================] - ETA: 0s - loss: 0.8681 - mean_iou: 0.2017 - dice_coef: 0.36592022-11-03 08:35:07.182277: W tensorflow/core/grappler/optimizers/data/auto_shard.cc:695] AUTO sharding policy will apply DATA sharding policy as it failed to apply FILE sharding policy because of the following reason: Found an unshardable source dataset: name: "TensorSliceDataset/_1"
op: "TensorSliceDataset"
input: "Placeholder/_0"
attr {
  key: "Toutput_types"
  value {
    list {
      type: DT_STRING
    }
  }
}
attr {
  key: "output_shapes"
  value {
    list {
      shape {
      }
    }
  }
}

Traceback (most recent call last):
  File "/dartfs/rc/lab/V/VecchioJ/arctic_image_segmentation/joanmarie_dev/segmentation_gym/train_model.py", line 756, in <module>
    history = model.fit(train_ds, steps_per_epoch=steps_per_epoch, epochs=MAX_EPOCHS,
  File "/dartfs-hpc/rc/home/1/f005dv1/.conda/envs/gym/lib/python3.9/site-packages/keras/engine/training.py", line 1215, in fit
    val_logs = self.evaluate(
  File "/dartfs-hpc/rc/home/1/f005dv1/.conda/envs/gym/lib/python3.9/site-packages/keras/engine/training.py", line 1501, in evaluate
    tmp_logs = self.test_function(iterator)
  File "/dartfs-hpc/rc/home/1/f005dv1/.conda/envs/gym/lib/python3.9/site-packages/tensorflow/python/eager/def_function.py", line 885, in __call__
    result = self._call(*args, **kwds)
  File "/dartfs-hpc/rc/home/1/f005dv1/.conda/envs/gym/lib/python3.9/site-packages/tensorflow/python/eager/def_function.py", line 924, in _call
    results = self._stateful_fn(*args, **kwds)
  File "/dartfs-hpc/rc/home/1/f005dv1/.conda/envs/gym/lib/python3.9/site-packages/tensorflow/python/eager/function.py", line 3039, in __call__
    return graph_function._call_flat(
  File "/dartfs-hpc/rc/home/1/f005dv1/.conda/envs/gym/lib/python3.9/site-packages/tensorflow/python/eager/function.py", line 1963, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "/dartfs-hpc/rc/home/1/f005dv1/.conda/envs/gym/lib/python3.9/site-packages/tensorflow/python/eager/function.py", line 591, in call
    outputs = execute.execute(
  File "/dartfs-hpc/rc/home/1/f005dv1/.conda/envs/gym/lib/python3.9/site-packages/tensorflow/python/eager/execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError: 5 root error(s) found.
  (0) Invalid argument:  Cannot batch tensors with different shapes in component 0. First element had shape [512,512,3] and element 1 had shape [512,512,1].
         [[{{node MultiDeviceIteratorGetNextFromShard}}]]
         [[RemoteCall]]
         [[IteratorGetNext]]
  (1) Invalid argument:  Cannot batch tensors with different shapes in component 0. First element had shape [512,512,3] and element 1 had shape [512,512,1].
         [[{{node MultiDeviceIteratorGetNextFromShard}}]]
         [[RemoteCall]]
         [[IteratorGetNext]]
         [[div_no_nan_2/_175]]
  (2) Invalid argument:  Cannot batch tensors with different shapes in component 0. First element had shape [512,512,3] and element 1 had shape [512,512,1].
         [[{{node MultiDeviceIteratorGetNextFromShard}}]]
         [[RemoteCall]]
         [[IteratorGetNext]]
         [[div_no_nan_2/_179]]
  (3) Invalid argument:  Cannot batch tensors with different shapes in component 0. First element had shape [512,512,3] and element 1 had shape [512,512,1].
         [[{{node MultiDeviceIteratorGetNextFromShard}}]]
         [[RemoteCall]]
         [[IteratorGetNext]]
         [[div_no_nan_2/_171]]
  (4) Invalid argument:  Cannot batch tensors with different shapes in component 0. First element had shape [512,512,3] and element 1 had shape [512,512,1].
         [[{{node MultiDeviceIteratorGetNextFromShard}}]]
         [[RemoteCall]]
         [[IteratorGetNext]]
         [[div_no_nan/ReadVariableOp_4/_182]]
0 successful operations.
0 derived errors ignored. [Op:__inference_test_function_88130]

Function call stack:
test_function -> test_function -> test_function -> test_function -> test_function
